#!/usr/bin/env python

from check_splunk import CheckSplunk
import sys


SPLUNK_SERVER = sys.argv[1]
SPLUNK_USERNAME = sys.argv[2]
SPLUNK_PASSWORD = sys.argv[3]
try:
	SPLUNK_LICENSE = sys.argv[4]
except:
    print "Missing required argument - license hash"

WARN_DAYS = 60
CRIT_DAYS = 30


args = [
    "-H", SPLUNK_SERVER,
    "-u", SPLUNK_USERNAME,
    "-p", SPLUNK_PASSWORD,
    "-L", SPLUNK_LICENSE,
    "-W", str(WARN_DAYS),
    "-C", str(CRIT_DAYS),
]

CheckSplunk(args).check_license_expiration().exit()
